# Generated by Django 4.2.6 on 2023-10-26 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Taikyoku4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonScore', models.IntegerField()),
                ('NanScore', models.IntegerField()),
                ('SyaScore', models.IntegerField()),
                ('PeScore', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PunPals.room')),
                ('userNan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taikyoku4_userNan', to='PunPals.user')),
                ('userPe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taikyoku4_userPei', to='PunPals.user')),
                ('userSya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taikyoku4_userSya', to='PunPals.user')),
                ('userTon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taikyoku4_userTon', to='PunPals.user')),
            ],
        ),
        migrations.CreateModel(
            name='Taikyoku3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonScore', models.IntegerField()),
                ('nanScore', models.IntegerField()),
                ('syaScore', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PunPals.room')),
                ('userNan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taikyoku3_userNan', to='PunPals.user')),
                ('userSya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiakyoku3_userSya', to='PunPals.user')),
                ('userTon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taikyoku3_userTon', to='PunPals.user')),
            ],
        ),
        migrations.CreateModel(
            name='Senseki4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankMean', models.FloatField()),
                ('firstNum', models.IntegerField()),
                ('secondNum', models.IntegerField()),
                ('thirdNum', models.IntegerField()),
                ('fourthNum', models.IntegerField()),
                ('firstRate', models.FloatField()),
                ('secondRate', models.FloatField()),
                ('thirdRate', models.FloatField()),
                ('fourthRate', models.FloatField()),
                ('outRate', models.FloatField()),
                ('gameNum', models.IntegerField()),
                ('scoreMean', models.FloatField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PunPals.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PunPals.user')),
            ],
        ),
        migrations.CreateModel(
            name='Senseki3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankMean', models.FloatField()),
                ('firstNum', models.IntegerField()),
                ('secondNum', models.IntegerField()),
                ('thirdNum', models.IntegerField()),
                ('firstRate', models.FloatField()),
                ('secondRate', models.FloatField()),
                ('thirdRate', models.FloatField()),
                ('outRate', models.FloatField()),
                ('gameNum', models.IntegerField()),
                ('scoreMean', models.FloatField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PunPals.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PunPals.user')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(to='PunPals.user'),
        ),
    ]
